### PR TITLE
Add Browser environment support

### PR DESCRIPTION
**Pull request by Soremwar**
Many API's enabled so far, but I've experienced many oddities that have required me to switch somethings around in order to make this first draft work.

Also there is a small modification to the definition load system, so that it loads automatically the global definition file for each supported environmente (to be reworked in a cleaner way).

Uses TypeScript 3.9 DOM typings.

Every commit from "typings" and forward works for testing.

### CODE REVIEW

**Comment by Soremwar** [comment]
@JSMonk I'm having some issues with things like interfaces extending from Node element. Apparently there is a check in type-utils.js that is preventing them to do so, but I can't quite figure out what is happening here: https://github.com/JSMonk/hegel/blob/2a939543c1de238517a2000d90566e8cc614ca7d/packages/core/src/utils/type-utils.js#L910 in the `getPropertiesForType`.

Care to explain? Wanna sort this out

**Comment by JSMonk** [comment]
OH MY GOOD!
You are my hero!
I really glad, that somebody helps me with it.
You are awesome ❤️
I will check the code today.
Thank you a lot.

**Comment by JSMonk** [comment]
> @JSMonk I'm having some issues with things like interfaces extending from Node element. Apparently there is a check in type-utils.js that is preventing them to do so, but I can't quite figure out what is happening in this function:
> 
> https://github.com/JSMonk/hegel/blob/2a939543c1de238517a2000d90566e8cc614ca7d/packages/core/src/utils/type-utils.js#L910-L935
> 
> Care to explain how this switch function works? Really want to sort this out

Yes. It's because we still have problem with with recurrent using of types:
Example:
```ts
interface Node {
  nextElementSibling: Element;
}

interface Element extends Node {}
```

1. We try to analyze `Node` interface.
2. We find `Element` property inside `Node`, so, try to analyze `Element`; `Node` in pending
3. We try to get `extends` parameter - it's `Node`.
4. `Node` is in pending, so we can't extend `Element` from it.
5. Fail.

We try to solve the problem by prototype chaining (like objects in JavaScript), but for now, it still not solved.

There are two solutions:
1. Try to rewrite typings without compositions like in the example.
2. Solve the recurrent problem.

**Comment by Soremwar** [comment]
Oh, so it's an issue with circular dependencies, got it

Prototyping might work for now, but a possible rework of the AST parser should be the way to go

Should things like Record be disallowed in definition files though? Or what is the current mindset on specific TS functionality in those files according to Hegel

**Comment by JSMonk** [comment]
> Oh, so it's an issue with circular dependencies, got it
> 
> Prototyping might work for now, but a possible rework of the AST parser should be the way to go
> 
> Should things like Record be disallowed in definition files though? Or what is the current mindset on specific TS functionality in those files according to Hegel

I hope, we will support everything except `namespace` and `conditional types`.

**Comment by Soremwar** [comment]
Ok.

I think this PR as of now should suffice for the basic needs of some people who want to try out the project, however for the sake of mantainability I wouldn't push forward any further 'til the AST issue is solved

Do you have any platform we can chat on to have some more clarity on where to go from here? I have some doubts regarding the parsing of d.ts and types in general I wanna sort out

**Comment by JSMonk** [comment]
> Ok.
> 
> I think this PR as of now should suffice for the basic needs of some people who want to try out the project, however for the sake of mantainability I wouldn't push forward any further 'til the AST issue is solved
> 
> Do you have any platform we can chat on to have some more clarity on where to go from here? I have some doubts regarding the parsing of d.ts and types in general I wanna sort out

Yes, you can ping me in Telegram (@js_monk) or on Twitter (@rage_monk)

**Comment by mohsen1** [comment]
I don't think checking in that big file is a good idea. You probably want to use automation for this. See https://github.com/microsoft/TSJS-lib-generator

**Comment by Soremwar** [comment]
The problem is, as of now Hegel doesn't support 100% d.ts files, there is a blocker to finish this PR.

That tool might give a positive validation, but this problem must be solved before we can just load the Dom types into Hegel.

**Comment by mohsen1** [comment]
My suggestion is to fork the tool and make it generate Hegel compatible types.

**Comment by JSMonk** [comment]
> My suggestion is to fork the tool and make it generate Hegel compatible types.

Currently, we are developing a better solution based on Hegel, which will be the first step of Hegel popularization.
With our type of inference, we can generate better `d.ts` for pure JavaScript projects (without a lot of any).

**Pull request closed without merging**
